name: Auto Create PR

on:
  push:
    branches:
      - 'React-Front_*'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Extract Branch Name
        run: echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Merge - ${{ env.BRANCH_NAME }}"
          pr_body: "${{ env.BRANCH_NAME }} will be merged."
          pr_label: "automerge, deploy"
