name: Run Notion API Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "NOTION_TOKEN=${{ secrets.Notion_Token }}" >> $GITHUB_ENV
        echo "NOTION_DATABASE_ID=${{ secrets.Notion_Database_ID }}" >> $GITHUB_ENV

    - name: Run script
      run: python Google-DSC-Kookmin.github.io/.github/Scripts/StoreNotionDB.py

env:
  NOTION_TOKEN: ${{ secrets.Notion_Token }}
  NOTION_DATABASE_ID: ${{ secrets.Notion_Database_ID }}
