name: Automatically GDSC Member Data Update

on:
  schedule:
    - cron: '0 0 1 */3 *'  # 매 3개월마다 1일에 실행
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Change to the repository directory
        run: cd Google-DSC-Kookmin.github.io

      - name: Setting .secrets.json
        run: |
          echo ${{ secrets.Notion_Token }} > .secrets.json
          echo ${{ secrets.Notion_Database_ID }} >> .secrets.json

      - name: Run script
        run: python storeNotionDB.py
